import * as XLSX from 'xlsx';
import type { DayOfWeek, ParsedCell, ParsedTeacher, ParseResult } from './types';

// Column layout in the smart schedule sheet:
//   col 1 (A) = serial number
//   col 2 (B) = teacher name
//   cols 3..9   = Sunday    periods 1..7
//   cols 10..16 = Monday    periods 1..7
//   cols 17..23 = Tuesday   periods 1..7
//   cols 24..30 = Wednesday periods 1..7
//   cols 31..37 = Thursday  periods 1..7
//   col 38 = total period count (informational)
const DAYS_LAYOUT: { day: DayOfWeek; firstCol: number }[] = [
  { day: 0, firstCol: 3 },
  { day: 1, firstCol: 10 },
  { day: 2, firstCol: 17 },
  { day: 3, firstCol: 24 },
  { day: 4, firstCol: 31 },
];
const PERIODS_PER_DAY = 7;

// "2 / 3" or "2/3" or "2 /3" — also tolerates Arabic-Indic digits.
const SECTION_PATTERN = /(\d+)\s*\/\s*(\d+)/;
const MONITORING_PATTERN = /منتظر\s*(\d+)/;

/**
 * Parse a smart-schedule .xlsx file (the format generated by the
 * "الجدول الذكي" Excel template the school uses) into a flat list of
 * teacher × cell records. Never throws on malformed cells — collects
 * issues into `warnings` so the admin can review before committing.
 */
export function parseScheduleWorkbook(buffer: Buffer): ParseResult {
  const wb = XLSX.read(buffer, { type: 'buffer', cellDates: false });
  const sheetName = wb.SheetNames[0];
  if (!sheetName) {
    return {
      teachers: [],
      warnings: ['الملف فارغ — لا يحتوي على أوراق'],
      meta: { rows_scanned: 0, days_detected: 0, periods_per_day: 0 },
    };
  }
  const sheet = wb.Sheets[sheetName];

  // Read as a 2D matrix using cell-A1 keys. xlsx returns each row as an
  // object indexed by column letter; we use sheet_to_json with header:1
  // to get plain arrays.
  const rows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: true, defval: null });

  const warnings: string[] = [];
  const teachers: ParsedTeacher[] = [];

  // The data starts at Excel row 4 (index 3). Rows 1-3 are headers.
  for (let r = 3; r < rows.length; r++) {
    const row = rows[r] || [];
    const nameCell = row[1];  // col B = index 1
    const teacherName = (nameCell == null ? '' : String(nameCell)).trim();
    if (!teacherName) continue;  // empty rows are fine, skip silently

    const cells: ParsedCell[] = [];
    let classCount = 0, monitoringCount = 0, freeCount = 0;

    for (const { day, firstCol } of DAYS_LAYOUT) {
      for (let p = 0; p < PERIODS_PER_DAY; p++) {
        // Excel cols are 1-indexed; sheet_to_json produces 0-indexed arrays.
        const colIndex = firstCol - 1 + p;
        const raw = row[colIndex];
        const cell = parseCell(raw, day, p + 1);
        cells.push(cell);
        if (cell.duty_type === 'class') classCount++;
        else if (cell.duty_type === 'monitoring') monitoringCount++;
        else freeCount++;
      }
    }

    teachers.push({
      rowIndex: r + 1,  // 1-based for the user
      teacher_name: teacherName,
      cells,
      total_class_periods: classCount,
      total_monitoring: monitoringCount,
      total_free: freeCount,
    });
  }

  if (teachers.length === 0) {
    warnings.push('لم يتم العثور على أي معلم في الملف. تأكد أن أسماء المعلمين تبدأ من الصف ٤ في العمود ب.');
  }

  return {
    teachers,
    warnings,
    meta: {
      rows_scanned: rows.length,
      days_detected: DAYS_LAYOUT.length,
      periods_per_day: PERIODS_PER_DAY,
    },
  };
}

/**
 * Classify a single Excel cell into class / monitoring / free.
 * Cells contain either:
 *   • Empty / whitespace            → free
 *   • "منتظر N"                      → monitoring of section N
 *   • "X / Y\n<subject>"             → class for grade X section Y
 */
function parseCell(rawValue: unknown, day: DayOfWeek, period: number): ParsedCell {
  const text = (rawValue == null ? '' : String(rawValue)).trim();

  if (text.length === 0) {
    return {
      day_of_week: day,
      period_number: period,
      duty_type: 'free',
      grade_label: null,
      section_label: null,
      subject: null,
      monitoring_target: null,
      raw: '',
    };
  }

  const monMatch = text.match(MONITORING_PATTERN);
  if (monMatch) {
    return {
      day_of_week: day,
      period_number: period,
      duty_type: 'monitoring',
      grade_label: null,
      section_label: null,
      subject: null,
      monitoring_target: parseInt(monMatch[1], 10),
      raw: text,
    };
  }

  const secMatch = text.match(SECTION_PATTERN);
  if (secMatch) {
    // The subject is everything AFTER the first "X / Y" — the Excel
    // uses "\n" but XLSX may normalize to space; we keep it loose.
    const afterMatch = text.slice((secMatch.index || 0) + secMatch[0].length).trim();
    const subject = afterMatch.length > 0 ? afterMatch.split(/\s{2,}|\n/)[0].trim() : null;
    return {
      day_of_week: day,
      period_number: period,
      duty_type: 'class',
      grade_label: secMatch[1],
      section_label: secMatch[2],
      subject: subject || null,
      monitoring_target: null,
      raw: text,
    };
  }

  // Unrecognized — fall back to free, but keep the raw text so admin
  // sees what was there.
  return {
    day_of_week: day,
    period_number: period,
    duty_type: 'free',
    grade_label: null,
    section_label: null,
    subject: null,
    monitoring_target: null,
    raw: text,
  };
}
