-- Safe academic-year rollover.
-- Keeps operational history intact, snapshots every student's grade/section
-- per year, and replaces the legacy in-place-only promotion workflow.

CREATE TABLE IF NOT EXISTS public.academic_years (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'planned'
    CHECK (status IN ('planned', 'open', 'closed', 'cancelled')),
  opened_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT academic_year_dates_valid CHECK (end_date > start_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS academic_years_one_open_idx
  ON public.academic_years ((status)) WHERE status = 'open';

ALTER TABLE public.school_settings
  ADD COLUMN IF NOT EXISTS academic_year_id BIGINT
  REFERENCES public.academic_years(id) ON DELETE RESTRICT;

-- Backfill the existing settings label as the first open year. The dates are
-- metadata defaults only; administrators choose exact dates for future years.
WITH current_settings AS (
  SELECT
    COALESCE(NULLIF(trim(academic_year), ''),
      extract(year FROM current_date)::INT::TEXT || '-' ||
      (extract(year FROM current_date)::INT + 1)::TEXT) AS year_name
  FROM public.school_settings
  WHERE id = 1
), normalized AS (
  SELECT
    year_name,
    CASE WHEN year_name ~ '^\d{4}-\d{4}$'
      THEN make_date(left(year_name, 4)::INT, 8, 1)
      ELSE current_date
    END AS starts_on,
    CASE WHEN year_name ~ '^\d{4}-\d{4}$'
      THEN make_date(right(year_name, 4)::INT, 7, 31)
      ELSE current_date + 365
    END AS ends_on
  FROM current_settings
)
INSERT INTO public.academic_years (name, start_date, end_date, status, opened_at)
SELECT year_name, starts_on, ends_on, 'open', now()
FROM normalized
ON CONFLICT (name) DO UPDATE
SET status = CASE
      WHEN public.academic_years.status IN ('planned', 'cancelled') THEN 'open'
      ELSE public.academic_years.status
    END,
    opened_at = COALESCE(public.academic_years.opened_at, now()),
    updated_at = now();

UPDATE public.school_settings ss
SET academic_year_id = ay.id,
    academic_year = ay.name,
    updated_at = now()
FROM public.academic_years ay
WHERE ss.id = 1
  AND ay.name = COALESCE(NULLIF(trim(ss.academic_year), ''), ay.name)
  AND ay.status = 'open'
  AND ss.academic_year_id IS NULL;

CREATE TABLE IF NOT EXISTS public.student_academic_year_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year_id BIGINT NOT NULL REFERENCES public.academic_years(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  grade_id INTEGER REFERENCES public.grades(id) ON DELETE SET NULL,
  section_id INTEGER REFERENCES public.sections(id) ON DELETE SET NULL,
  grade_name VARCHAR(100),
  section_name VARCHAR(100),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'completed', 'graduated', 'inactive', 'transferred')),
  source TEXT NOT NULL DEFAULT 'automatic'
    CHECK (source IN ('backfill', 'rollover', 'automatic', 'manual', 'import')),
  started_at DATE NOT NULL DEFAULT current_date,
  ended_at DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (academic_year_id, student_id)
);

CREATE INDEX IF NOT EXISTS student_year_enrollments_student_idx
  ON public.student_academic_year_enrollments (student_id, academic_year_id DESC);
CREATE INDEX IF NOT EXISTS student_year_enrollments_scope_idx
  ON public.student_academic_year_enrollments (academic_year_id, grade_id, section_id, status);

INSERT INTO public.student_academic_year_enrollments (
  academic_year_id, student_id, grade_id, section_id,
  grade_name, section_name, status, source, started_at
)
SELECT
  ss.academic_year_id,
  s.id,
  s.grade_id,
  s.section_id,
  g.name,
  sec.name,
  'active',
  'backfill',
  ay.start_date
FROM public.school_settings ss
JOIN public.academic_years ay ON ay.id = ss.academic_year_id
JOIN public.students s ON s.is_active IS NOT FALSE
LEFT JOIN public.grades g ON g.id = s.grade_id
LEFT JOIN public.sections sec ON sec.id = s.section_id
WHERE ss.id = 1
ON CONFLICT (academic_year_id, student_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.academic_year_rollovers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key UUID NOT NULL UNIQUE,
  from_academic_year_id BIGINT NOT NULL REFERENCES public.academic_years(id) ON DELETE RESTRICT,
  to_academic_year_id BIGINT NOT NULL REFERENCES public.academic_years(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'reversed', 'failed')),
  promoted_count INTEGER NOT NULL DEFAULT 0,
  graduated_count INTEGER NOT NULL DEFAULT 0,
  unassigned_section_count INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  reversed_at TIMESTAMPTZ,
  summary JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE UNIQUE INDEX IF NOT EXISTS academic_year_rollovers_one_completed_from_idx
  ON public.academic_year_rollovers (from_academic_year_id)
  WHERE status = 'completed';

CREATE TABLE IF NOT EXISTS public.academic_year_rollover_students (
  rollover_id UUID NOT NULL REFERENCES public.academic_year_rollovers(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  previous_grade_id INTEGER REFERENCES public.grades(id) ON DELETE SET NULL,
  previous_section_id INTEGER REFERENCES public.sections(id) ON DELETE SET NULL,
  previous_is_active BOOLEAN NOT NULL,
  previous_is_fingerprint_enrolled BOOLEAN NOT NULL,
  previous_enrolled_at TIMESTAMPTZ,
  action TEXT CHECK (action IN ('promoted', 'graduated')),
  new_grade_id INTEGER REFERENCES public.grades(id) ON DELETE SET NULL,
  new_section_id INTEGER REFERENCES public.sections(id) ON DELETE SET NULL,
  new_is_active BOOLEAN,
  PRIMARY KEY (rollover_id, student_id)
);

ALTER TABLE public.academic_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_academic_year_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_year_rollovers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_year_rollover_students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS academic_years_read ON public.academic_years;
CREATE POLICY academic_years_read ON public.academic_years
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS academic_years_admin_write ON public.academic_years;
CREATE POLICY academic_years_admin_write ON public.academic_years
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

DROP POLICY IF EXISTS student_year_enrollments_admin_read ON public.student_academic_year_enrollments;
CREATE POLICY student_year_enrollments_admin_read ON public.student_academic_year_enrollments
  FOR SELECT TO authenticated USING (is_admin());

DROP POLICY IF EXISTS academic_year_rollovers_admin_read ON public.academic_year_rollovers;
CREATE POLICY academic_year_rollovers_admin_read ON public.academic_year_rollovers
  FOR SELECT TO authenticated USING (is_admin());

DROP POLICY IF EXISTS academic_year_rollover_students_admin_read ON public.academic_year_rollover_students;
CREATE POLICY academic_year_rollover_students_admin_read ON public.academic_year_rollover_students
  FOR SELECT TO authenticated USING (is_admin());

-- Keep the current-year enrollment snapshot synchronized for new students and
-- mid-year section changes. The rollover RPC temporarily disables this trigger
-- and writes both year snapshots itself.
CREATE OR REPLACE FUNCTION public.sync_current_student_year_enrollment()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_year_id BIGINT;
  v_start_date DATE;
  v_grade_name TEXT;
  v_section_name TEXT;
BEGIN
  IF current_setting('app.academic_year_rollover', true) = 'on' THEN
    RETURN NEW;
  END IF;

  SELECT ay.id, ay.start_date
  INTO v_year_id, v_start_date
  FROM school_settings ss
  JOIN academic_years ay ON ay.id = ss.academic_year_id
  WHERE ss.id = 1 AND ay.status = 'open';

  IF v_year_id IS NULL THEN RETURN NEW; END IF;

  SELECT name INTO v_grade_name FROM grades WHERE id = NEW.grade_id;
  SELECT name INTO v_section_name FROM sections WHERE id = NEW.section_id;

  IF NEW.is_active IS NOT FALSE THEN
    INSERT INTO student_academic_year_enrollments (
      academic_year_id, student_id, grade_id, section_id,
      grade_name, section_name, status, source, started_at, ended_at, updated_at
    ) VALUES (
      v_year_id, NEW.id, NEW.grade_id, NEW.section_id,
      v_grade_name, v_section_name, 'active', 'automatic', v_start_date, NULL, now()
    )
    ON CONFLICT (academic_year_id, student_id) DO UPDATE SET
      grade_id = EXCLUDED.grade_id,
      section_id = EXCLUDED.section_id,
      grade_name = EXCLUDED.grade_name,
      section_name = EXCLUDED.section_name,
      status = 'active',
      ended_at = NULL,
      updated_at = now();
  ELSE
    UPDATE student_academic_year_enrollments
    SET status = CASE WHEN status = 'graduated' THEN status ELSE 'inactive' END,
        ended_at = COALESCE(ended_at, current_date),
        updated_at = now()
    WHERE academic_year_id = v_year_id AND student_id = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS students_sync_current_academic_year ON public.students;
CREATE TRIGGER students_sync_current_academic_year
AFTER INSERT OR UPDATE OF grade_id, section_id, is_active ON public.students
FOR EACH ROW EXECUTE FUNCTION public.sync_current_student_year_enrollment();

CREATE OR REPLACE FUNCTION public.preview_academic_year_rollover()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_stage TEXT;
  v_max_order INTEGER;
  v_current_year JSONB;
  v_preview JSONB;
  v_total INTEGER;
  v_graduated INTEGER;
  v_devices INTEGER;
BEGIN
  IF NOT is_admin() THEN RAISE EXCEPTION 'forbidden: admin role required'; END IF;

  SELECT stage INTO v_stage FROM school_settings WHERE id = 1;
  SELECT MAX(sort_order) INTO v_max_order FROM grades WHERE stage = v_stage;
  IF v_stage IS NULL OR v_max_order IS NULL THEN
    RAISE EXCEPTION 'school stage or grades not configured';
  END IF;

  SELECT jsonb_build_object(
    'id', ay.id, 'name', ay.name, 'start_date', ay.start_date,
    'end_date', ay.end_date, 'status', ay.status
  ) INTO v_current_year
  FROM school_settings ss
  JOIN academic_years ay ON ay.id = ss.academic_year_id
  WHERE ss.id = 1;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'grade_id', q.id,
    'grade_name', q.name,
    'student_count', q.student_count,
    'action', CASE WHEN q.sort_order = v_max_order THEN 'graduate' ELSE 'promote' END,
    'next_grade_name', q.next_grade_name
  ) ORDER BY q.sort_order DESC), '[]'::JSONB)
  INTO v_preview
  FROM (
    SELECT g.id, g.name, g.sort_order,
      (SELECT count(*)::INT FROM students s
       WHERE s.grade_id = g.id AND s.is_active IS NOT FALSE) AS student_count,
      ng.name AS next_grade_name
    FROM grades g
    LEFT JOIN grades ng ON ng.stage = g.stage AND ng.sort_order = g.sort_order + 1
    WHERE g.stage = v_stage
  ) q;

  SELECT count(*)::INT INTO v_total FROM students WHERE is_active IS NOT FALSE;
  SELECT count(*)::INT INTO v_graduated
  FROM students s JOIN grades g ON g.id = s.grade_id
  WHERE s.is_active IS NOT FALSE AND g.stage = v_stage AND g.sort_order = v_max_order;
  SELECT count(*)::INT INTO v_devices FROM devices WHERE section_id IS NOT NULL AND is_active IS NOT FALSE;

  RETURN jsonb_build_object(
    'current_year', v_current_year,
    'preview', v_preview,
    'total_students', v_total,
    'graduated_count', v_graduated,
    'promoted_count', GREATEST(v_total - v_graduated, 0),
    'devices_to_resync', v_devices
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.open_next_academic_year(
  p_new_year_name TEXT,
  p_start_date DATE,
  p_end_date DATE,
  p_idempotency_key UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_settings school_settings%ROWTYPE;
  v_current academic_years%ROWTYPE;
  v_new academic_years%ROWTYPE;
  v_existing academic_year_rollovers%ROWTYPE;
  v_rollover_id UUID;
  v_stage TEXT;
  v_max_order INTEGER;
  v_grade RECORD;
  v_next_grade RECORD;
  v_section RECORD;
  v_target_section_id INTEGER;
  v_count INTEGER;
  v_promoted INTEGER := 0;
  v_graduated INTEGER := 0;
  v_unassigned INTEGER := 0;
  v_summary JSONB;
BEGIN
  IF NOT is_admin() THEN RAISE EXCEPTION 'forbidden: admin role required'; END IF;
  IF p_idempotency_key IS NULL THEN RAISE EXCEPTION 'idempotency key is required'; END IF;

  PERFORM pg_advisory_xact_lock(hashtext('academic-year-rollover'));

  SELECT * INTO v_existing
  FROM academic_year_rollovers WHERE idempotency_key = p_idempotency_key;
  IF FOUND AND v_existing.status = 'completed' THEN
    RETURN v_existing.summary;
  ELSIF FOUND THEN
    RAISE EXCEPTION 'this rollover request already exists with status %', v_existing.status;
  END IF;

  SELECT * INTO v_settings FROM school_settings WHERE id = 1 FOR UPDATE;
  IF NOT FOUND OR v_settings.academic_year_id IS NULL THEN
    RAISE EXCEPTION 'current academic year is not configured';
  END IF;
  SELECT * INTO v_current FROM academic_years WHERE id = v_settings.academic_year_id FOR UPDATE;
  IF v_current.status <> 'open' THEN RAISE EXCEPTION 'current academic year is not open'; END IF;

  p_new_year_name := trim(p_new_year_name);
  IF p_new_year_name !~ '^\d{4}-\d{4}$'
     OR right(p_new_year_name, 4)::INT <> left(p_new_year_name, 4)::INT + 1 THEN
    RAISE EXCEPTION 'academic year must use YYYY-YYYY with consecutive years';
  END IF;
  IF p_new_year_name = v_current.name THEN RAISE EXCEPTION 'new year must differ from current year'; END IF;
  IF p_end_date <= p_start_date THEN RAISE EXCEPTION 'end date must be after start date'; END IF;

  SELECT stage INTO v_stage FROM school_settings WHERE id = 1;
  SELECT MAX(sort_order) INTO v_max_order FROM grades WHERE stage = v_stage;
  IF v_max_order IS NULL THEN RAISE EXCEPTION 'no grades configured for school stage'; END IF;

  SELECT * INTO v_new FROM academic_years WHERE name = p_new_year_name FOR UPDATE;
  IF FOUND AND v_new.status NOT IN ('planned', 'cancelled') THEN
    RAISE EXCEPTION 'academic year % already exists with status %', p_new_year_name, v_new.status;
  ELSIF FOUND THEN
    UPDATE academic_years
    SET start_date = p_start_date, end_date = p_end_date,
        status = 'planned', opened_at = NULL, closed_at = NULL,
        created_by = auth.uid(), updated_at = now()
    WHERE id = v_new.id RETURNING * INTO v_new;
  ELSE
    INSERT INTO academic_years (name, start_date, end_date, status, created_by)
    VALUES (p_new_year_name, p_start_date, p_end_date, 'planned', auth.uid())
    RETURNING * INTO v_new;
  END IF;

  INSERT INTO academic_year_rollovers (
    idempotency_key, from_academic_year_id, to_academic_year_id, status, created_by
  ) VALUES (
    p_idempotency_key, v_current.id, v_new.id, 'running', auth.uid()
  ) RETURNING id INTO v_rollover_id;

  INSERT INTO academic_year_rollover_students (
    rollover_id, student_id, previous_grade_id, previous_section_id,
    previous_is_active, previous_is_fingerprint_enrolled, previous_enrolled_at
  )
  SELECT v_rollover_id, id, grade_id, section_id,
         COALESCE(is_active, true), COALESCE(is_fingerprint_enrolled, false), enrolled_at
  FROM students WHERE is_active IS NOT FALSE;

  INSERT INTO student_academic_year_enrollments (
    academic_year_id, student_id, grade_id, section_id,
    grade_name, section_name, status, source, started_at
  )
  SELECT v_current.id, s.id, s.grade_id, s.section_id,
         g.name, sec.name, 'active', 'backfill', v_current.start_date
  FROM students s
  LEFT JOIN grades g ON g.id = s.grade_id
  LEFT JOIN sections sec ON sec.id = s.section_id
  WHERE s.is_active IS NOT FALSE
  ON CONFLICT (academic_year_id, student_id) DO NOTHING;

  PERFORM set_config('app.academic_year_rollover', 'on', true);

  FOR v_grade IN
    SELECT id, name, sort_order FROM grades
    WHERE stage = v_stage ORDER BY sort_order DESC
  LOOP
    IF v_grade.sort_order = v_max_order THEN
      UPDATE students
      SET is_active = false,
          is_fingerprint_enrolled = false,
          enrolled_at = NULL,
          updated_at = now()
      WHERE grade_id = v_grade.id AND is_active IS NOT FALSE;
      GET DIAGNOSTICS v_count = ROW_COUNT;
      v_graduated := v_graduated + v_count;

      UPDATE academic_year_rollover_students
      SET action = 'graduated', new_grade_id = previous_grade_id,
          new_section_id = previous_section_id, new_is_active = false
      WHERE rollover_id = v_rollover_id AND previous_grade_id = v_grade.id;
    ELSE
      SELECT id, name INTO v_next_grade
      FROM grades WHERE stage = v_stage AND sort_order = v_grade.sort_order + 1 LIMIT 1;
      IF v_next_grade.id IS NULL THEN CONTINUE; END IF;

      FOR v_section IN SELECT id, name FROM sections WHERE grade_id = v_grade.id LOOP
        SELECT id INTO v_target_section_id
        FROM sections WHERE grade_id = v_next_grade.id AND name = v_section.name LIMIT 1;

        UPDATE students
        SET grade_id = v_next_grade.id,
            section_id = v_target_section_id,
            is_fingerprint_enrolled = false,
            enrolled_at = NULL,
            updated_at = now()
        WHERE section_id = v_section.id AND is_active IS NOT FALSE;
        GET DIAGNOSTICS v_count = ROW_COUNT;
        v_promoted := v_promoted + v_count;
        IF v_target_section_id IS NULL THEN v_unassigned := v_unassigned + v_count; END IF;
      END LOOP;

      UPDATE students
      SET grade_id = v_next_grade.id,
          section_id = NULL,
          is_fingerprint_enrolled = false,
          enrolled_at = NULL,
          updated_at = now()
      WHERE grade_id = v_grade.id AND section_id IS NULL AND is_active IS NOT FALSE;
      GET DIAGNOSTICS v_count = ROW_COUNT;
      v_promoted := v_promoted + v_count;
      v_unassigned := v_unassigned + v_count;

      UPDATE academic_year_rollover_students rs
      SET action = 'promoted',
          new_grade_id = s.grade_id,
          new_section_id = s.section_id,
          new_is_active = s.is_active
      FROM students s
      WHERE rs.rollover_id = v_rollover_id
        AND rs.student_id = s.id
        AND rs.previous_grade_id = v_grade.id;
    END IF;
  END LOOP;

  UPDATE student_academic_year_enrollments e
  SET status = CASE WHEN rs.action = 'graduated' THEN 'graduated' ELSE 'completed' END,
      ended_at = v_current.end_date,
      updated_at = now()
  FROM academic_year_rollover_students rs
  WHERE rs.rollover_id = v_rollover_id
    AND e.academic_year_id = v_current.id
    AND e.student_id = rs.student_id;

  UPDATE academic_years
  SET status = 'closed', closed_at = now(), updated_at = now()
  WHERE id = v_current.id;
  UPDATE academic_years
  SET status = 'open', opened_at = now(), closed_at = NULL, updated_at = now()
  WHERE id = v_new.id;
  UPDATE school_settings
  SET academic_year_id = v_new.id, academic_year = v_new.name, updated_at = now()
  WHERE id = 1;

  INSERT INTO student_academic_year_enrollments (
    academic_year_id, student_id, grade_id, section_id,
    grade_name, section_name, status, source, started_at
  )
  SELECT v_new.id, s.id, s.grade_id, s.section_id,
         g.name, sec.name, 'active', 'rollover', v_new.start_date
  FROM students s
  LEFT JOIN grades g ON g.id = s.grade_id
  LEFT JOIN sections sec ON sec.id = s.section_id
  WHERE s.is_active IS NOT FALSE
  ON CONFLICT (academic_year_id, student_id) DO UPDATE SET
    grade_id = EXCLUDED.grade_id,
    section_id = EXCLUDED.section_id,
    grade_name = EXCLUDED.grade_name,
    section_name = EXCLUDED.section_name,
    status = 'active',
    source = 'rollover',
    started_at = EXCLUDED.started_at,
    ended_at = NULL,
    updated_at = now();

  UPDATE devices
  SET status = 'disconnected', last_seen_at = NULL, updated_at = now()
  WHERE section_id IS NOT NULL;

  v_summary := jsonb_build_object(
    'rollover_id', v_rollover_id,
    'from_year', v_current.name,
    'to_year', v_new.name,
    'promoted', v_promoted,
    'graduated', v_graduated,
    'unassigned_sections', v_unassigned,
    'completed_at', now()
  );

  UPDATE academic_year_rollovers
  SET status = 'completed', promoted_count = v_promoted,
      graduated_count = v_graduated,
      unassigned_section_count = v_unassigned,
      completed_at = now(), summary = v_summary
  WHERE id = v_rollover_id;

  RETURN v_summary;
END;
$$;

CREATE OR REPLACE FUNCTION public.rollback_academic_year_rollover(p_rollover_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rollover academic_year_rollovers%ROWTYPE;
  v_from academic_years%ROWTYPE;
  v_to academic_years%ROWTYPE;
  v_restored INTEGER;
BEGIN
  IF NOT is_admin() THEN RAISE EXCEPTION 'forbidden: admin role required'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext('academic-year-rollover'));

  SELECT * INTO v_rollover FROM academic_year_rollovers
  WHERE id = p_rollover_id FOR UPDATE;
  IF NOT FOUND OR v_rollover.status <> 'completed' THEN
    RAISE EXCEPTION 'completed rollover not found';
  END IF;
  IF v_rollover.completed_at < now() - interval '24 hours' THEN
    RAISE EXCEPTION 'rollback window has expired';
  END IF;

  SELECT * INTO v_from FROM academic_years WHERE id = v_rollover.from_academic_year_id;
  SELECT * INTO v_to FROM academic_years WHERE id = v_rollover.to_academic_year_id;

  IF NOT EXISTS (
    SELECT 1 FROM school_settings
    WHERE id = 1 AND academic_year_id = v_to.id
  ) THEN RAISE EXCEPTION 'the rollover year is no longer current'; END IF;

  IF EXISTS (SELECT 1 FROM students WHERE created_at > v_rollover.completed_at)
     OR EXISTS (SELECT 1 FROM attendance_records WHERE created_at > v_rollover.completed_at)
     OR EXISTS (SELECT 1 FROM period_sessions WHERE recorded_at > v_rollover.completed_at)
     OR EXISTS (SELECT 1 FROM student_notes WHERE created_at > v_rollover.completed_at)
     OR EXISTS (SELECT 1 FROM student_dismissals WHERE created_at > v_rollover.completed_at)
     OR EXISTS (SELECT 1 FROM student_incidents WHERE created_at > v_rollover.completed_at)
     OR EXISTS (SELECT 1 FROM student_cases WHERE created_at > v_rollover.completed_at)
     OR EXISTS (
       SELECT 1 FROM student_academic_year_enrollments
       WHERE academic_year_id = v_to.id AND source <> 'rollover'
     ) THEN
    RAISE EXCEPTION 'new-year activity exists; rollback is blocked to protect data';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM academic_year_rollover_students rs
    JOIN students s ON s.id = rs.student_id
    WHERE rs.rollover_id = v_rollover.id
      AND (s.grade_id IS DISTINCT FROM rs.new_grade_id
        OR s.section_id IS DISTINCT FROM rs.new_section_id
        OR s.is_active IS DISTINCT FROM rs.new_is_active)
  ) THEN
    RAISE EXCEPTION 'student assignments changed after rollover; rollback is blocked';
  END IF;

  PERFORM set_config('app.academic_year_rollover', 'on', true);

  UPDATE students s
  SET grade_id = rs.previous_grade_id,
      section_id = rs.previous_section_id,
      is_active = rs.previous_is_active,
      is_fingerprint_enrolled = rs.previous_is_fingerprint_enrolled,
      enrolled_at = rs.previous_enrolled_at,
      updated_at = now()
  FROM academic_year_rollover_students rs
  WHERE rs.rollover_id = v_rollover.id AND rs.student_id = s.id;
  GET DIAGNOSTICS v_restored = ROW_COUNT;

  DELETE FROM student_academic_year_enrollments WHERE academic_year_id = v_to.id;
  UPDATE student_academic_year_enrollments
  SET status = 'active', ended_at = NULL, updated_at = now()
  WHERE academic_year_id = v_from.id;

  -- Close the new year before re-opening the old one so the partial unique
  -- index never observes two open years, even within this transaction.
  UPDATE academic_years
  SET status = 'cancelled', opened_at = NULL, closed_at = now(), updated_at = now()
  WHERE id = v_to.id;
  UPDATE academic_years
  SET status = 'open', closed_at = NULL, updated_at = now()
  WHERE id = v_from.id;
  UPDATE school_settings
  SET academic_year_id = v_from.id, academic_year = v_from.name, updated_at = now()
  WHERE id = 1;
  UPDATE academic_year_rollovers
  SET status = 'reversed', reversed_at = now()
  WHERE id = v_rollover.id;

  RETURN jsonb_build_object(
    'rollover_id', v_rollover.id,
    'restored_students', v_restored,
    'current_year', v_from.name,
    'reversed_at', now()
  );
END;
$$;

REVOKE ALL ON FUNCTION public.preview_academic_year_rollover() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.open_next_academic_year(TEXT, DATE, DATE, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rollback_academic_year_rollover(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.preview_academic_year_rollover() TO authenticated;
GRANT EXECUTE ON FUNCTION public.open_next_academic_year(TEXT, DATE, DATE, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rollback_academic_year_rollover(UUID) TO authenticated;

-- Prevent the old endpoint/RPC from bypassing annual snapshots.
REVOKE EXECUTE ON FUNCTION public.promote_students() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.promote_students() FROM authenticated;
