-- م4.2 — Student cases table.
--
-- The "case" is a long-lived record managed by a counselor: opened
-- from an incident escalation OR created directly, lives through
-- sessions + follow-up plans + notes, eventually resolved/closed.
--
-- Four-state lifecycle (state machine enforced in API via
-- lib/cases/state-machine.ts — م4.26):
--
--   open ──► in_progress ──► resolved ──► in_progress (reopen)
--                       └──► closed (terminal)
--
-- This migration creates ONLY the table + sequence + indexes + the
-- previously-deferred FK from student_incidents.case_id, plus enables
-- RLS fail-closed (no policies — those land in م4.7 separately).
-- pgcrypto (م4.1) and the other Sprint 4 migrations come as their
-- own files; this is the first Sprint 4 migration we ship.
--
-- Naming: `2026_06_10_001_*` matches the Sprint 2/3 batch ordering
-- convention. Alphabetical filename sort is the order Supabase CLI
-- applies migrations in, so a numeric prefix guarantees this lands
-- before sibling Sprint 4 files (002 = pgcrypto, 003 = case_history,
-- 004 = counseling_sessions, etc.).
--
-- FK behavior choices (carry-over from Sprint 3 review):
--   students(id)         → RESTRICT. Cases are historical; deleting
--                          a student must not silently drop their
--                          counseling record. Deactivate instead.
--   auth.users(id) for created_by → NOT NULL + NO ACTION. Every case
--                          has an opener; counselor deletion is rare
--                          (deactivate is the normal path).
--   related_case_id      → SET NULL. Linked cases can be archived
--                          without dropping the current row's reference.
--   student_incidents.case_id (back-FK added below) → SET NULL.
--                          Purging a closed case shouldn't lose the
--                          escalation record that fed it.

-- ============== Sequence for case_number ==============
-- Per-year reset (NNNN starts at 1 each Jan 1) is tech debt for
-- م4.27 (lib/cases/numbering.ts). For now a single monotonic
-- sequence + year prefix keeps numbers unique and sortable. The
-- year-portion in the DEFAULT below is computed at insert time
-- against the Riyadh calendar, so a row inserted on Jan 1 00:30 KSA
-- gets the new year prefix even if the UTC clock still reads
-- Dec 31.
-- Namespaced under the table to avoid future collisions (e.g. an
-- unrelated "case" feature later wanting its own counter). Codex
-- Sprint 4 review.
CREATE SEQUENCE IF NOT EXISTS student_cases_case_number_seq AS INTEGER MINVALUE 1 START 1;

-- ============== Table ==============
CREATE TABLE IF NOT EXISTS student_cases (
  id              BIGSERIAL PRIMARY KEY,

  -- User-visible identifier — CASE-YYYY-NNNN. Generated by the
  -- DEFAULT expression so any direct INSERT (manual, migration,
  -- backfill) gets a valid number without an API helper.
  case_number     TEXT NOT NULL UNIQUE DEFAULT (
    'CASE-' || EXTRACT(YEAR FROM (NOW() AT TIME ZONE 'Asia/Riyadh'))::TEXT
    || '-' || LPAD(nextval('student_cases_case_number_seq')::TEXT, 4, '0')
  ),

  -- Subject of the case
  student_id      INTEGER NOT NULL REFERENCES students(id) ON DELETE RESTRICT,

  -- Counselor / opener of the case
  created_by      UUID NOT NULL REFERENCES auth.users(id),

  -- ============== Content ==============
  -- title required, brief; description is the substantive narrative.
  -- Min lengths force meaningful entries (same enforcement style as
  -- student_incidents description ≥ 20).
  title           VARCHAR(200) NOT NULL CHECK (length(title) >= 10),
  description     TEXT NOT NULL CHECK (length(description) >= 20),

  case_type       VARCHAR(20) NOT NULL CHECK (case_type IN (
    'academic',    -- أكاديمي (تأخر تحصيلي، رسوب)
    'behavioral',  -- سلوكي (عدوانية، انعزال)
    'social',      -- اجتماعي (تنمر، صداقات)
    'health',      -- صحي (مزمن، نفسي)
    'family',      -- أسري (طلاق، وفاة)
    'attendance'   -- غياب متكرر
  )),

  severity        VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (severity IN (
    'low', 'medium', 'high', 'critical'
  )),

  -- ============== State machine ==============
  -- Enforced by CHECK + the م4.26 state-machine helper at the API
  -- layer. CHECK keeps direct DB writes honest (defense-in-depth).
  status          VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN (
    'open', 'in_progress', 'resolved', 'closed'
  )),

  -- ============== Terminal-state fields ==============
  -- resolution: required when status='resolved'. Nullable globally
  -- so the row can transit open → in_progress without filling it,
  -- but the partial-CHECK below enforces presence when terminal.
  resolution      TEXT,

  -- close_reason: required when status='closed'. Closed covers
  -- cancellation, duplicate, transfer — anything that ends the
  -- case without a meaningful "resolved" outcome.
  close_reason    TEXT,

  -- ============== Reopen tracking ==============
  -- A resolved case can be reopened (back to in_progress) if the
  -- problem recurs. We keep a counter + boolean snapshot so the UI
  -- can flag "this case was reopened N times" without re-aggregating
  -- the history table on every render.
  reopen_count    SMALLINT NOT NULL DEFAULT 0,
  is_reopened     BOOLEAN  NOT NULL DEFAULT FALSE,

  -- ============== Cross-case linkage ==============
  -- closed → new case may carry the prior case's context. The link
  -- is one-directional (new.related_case_id → old.id). SET NULL on
  -- delete so purging the old row doesn't break the chain.
  related_case_id BIGINT REFERENCES student_cases(id) ON DELETE SET NULL,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- ============== Conditional CHECK constraints ==============
  -- Status-conditional: resolved/closed require their justification
  -- column. The 20 / 5 char minimums force more than a single-word
  -- reason. Same defense-in-depth principle as the description
  -- length on student_incidents.
  CONSTRAINT cases_resolved_needs_resolution CHECK (
    status != 'resolved' OR (resolution IS NOT NULL AND length(resolution) >= 20)
  ),
  CONSTRAINT cases_closed_needs_close_reason CHECK (
    status != 'closed' OR (close_reason IS NOT NULL AND length(close_reason) >= 5)
  )
);

-- ============== Comments ==============
COMMENT ON TABLE student_cases IS
  'Counselor-managed cases for individual students. Lifecycle: open → in_progress → (resolved | closed). resolved cases can reopen → in_progress with reopen_count++. closed is terminal. RLS in م4.7. Case history trigger in м4.3. Linked tables (sessions/plans/incidents) reference id; incidents.case_id FK is added by THIS migration.';

COMMENT ON COLUMN student_cases.case_number IS
  'User-visible identifier (CASE-YYYY-NNNN). The DEFAULT composes the year (Riyadh calendar) with nextval(student_cases_case_number_seq). Per-year reset of NNNN is tech debt (م4.27); for now the sequence keeps growing — uniqueness and sortability are still correct.';

COMMENT ON COLUMN student_cases.related_case_id IS
  'Optional link to a prior case (typically closed) whose context carries forward to this one. SET NULL on delete so old-case purge does not break the new case.';

-- ============== Indexes ==============

-- 1. Active-case lists (the hot path for counselor dashboards).
--    Partial index on the non-terminal states keeps it small.
CREATE INDEX IF NOT EXISTS idx_cases_active
  ON student_cases (status, updated_at DESC)
  WHERE status IN ('open', 'in_progress');

-- 2. Per-student history (case detail page + Sprint 5 risk score).
CREATE INDEX IF NOT EXISTS idx_cases_student
  ON student_cases (student_id, created_at DESC);

-- 3. "My cases" view for the counselor (filter by opener).
CREATE INDEX IF NOT EXISTS idx_cases_created_by
  ON student_cases (created_by, created_at DESC);

-- 4. Case-type filter for triage dashboards.
CREATE INDEX IF NOT EXISTS idx_cases_type
  ON student_cases (case_type, status);

-- 5. Reverse-link lookup (which case spawned this new one).
CREATE INDEX IF NOT EXISTS idx_cases_related
  ON student_cases (related_case_id)
  WHERE related_case_id IS NOT NULL;

-- ============== updated_at trigger ==============
-- The idx_cases_active index sorts by updated_at DESC, which is
-- only meaningful if the column actually reflects the last write.
-- Without a trigger, the API would have to remember to set it on
-- every UPDATE — easy to forget on partial-column patches. A
-- BEFORE UPDATE trigger that always bumps the timestamp is
-- defense-in-depth: any write path (API, manual SQL, future
-- service) keeps the index honest (Codex Sprint 4 review).
--
-- SECURITY DEFINER + search_path locked — same pattern as Sprint 1
-- helpers and the m3.3 status-history trigger.
CREATE OR REPLACE FUNCTION student_cases_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION student_cases_set_updated_at() IS
  'BEFORE UPDATE trigger function on student_cases — bumps updated_at to NOW(). Keeps idx_cases_active sortable without relying on every API caller to set the column manually.';

DROP TRIGGER IF EXISTS student_cases_updated_at_trigger ON student_cases;
CREATE TRIGGER student_cases_updated_at_trigger
  BEFORE UPDATE ON student_cases
  FOR EACH ROW
  EXECUTE FUNCTION student_cases_set_updated_at();

-- ============== Sprint 3 carry-over: incidents.case_id FK ==============
-- The student_incidents.case_id column was created in Sprint 3 as a
-- bare BIGINT with no FK ("FK added in Sprint 4" comment in
-- 2026_06_03_001_student_incidents.sql). Wire it up now that
-- student_cases exists. SET NULL on delete so a future purge of a
-- closed case leaves the original incident intact (the incident is
-- still a valid historical record; it just no longer points to a
-- case).
--
-- Idempotent: check pg_constraint before adding so re-running the
-- migration is safe.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'incidents_case_id_fk'
      AND conrelid = 'student_incidents'::regclass
  ) THEN
    ALTER TABLE student_incidents
      ADD CONSTRAINT incidents_case_id_fk
      FOREIGN KEY (case_id) REFERENCES student_cases(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- ============== Fail-closed RLS default ==============
-- Enable RLS now, WITHOUT any policies. RLS-with-no-policies is the
-- strictest possible state: every `authenticated` query returns
-- zero rows / fails — including queries from an app-layer
-- "super_admin" user (the app's role claim has no effect on RLS;
-- only the PostgreSQL connection role does). Reads/writes work
-- ONLY via:
--   - service-role connection (createAdminSupabaseClient — bypasses
--     RLS by design), or
--   - the table owner (postgres, used by migrations).
--
-- So between THIS migration shipping and م4.7 wiring real policies,
-- the table is invisible to every regular user. That's the failsafe
-- if м4.7 lags — same fail-closed pattern as student_incidents
-- before its m3.2 (Codex Sprint 4 review correction).
ALTER TABLE student_cases ENABLE ROW LEVEL SECURITY;
